### ISSUE TITLE
Not working locally ?

### ISSUE THREAD

**Issue by fro-profesional** [brillout/vps-deno#1]
Tried to run locally but getting

```
  VITE v4.0.3  ready in 1887 ms

  ➜  Local:   http://localhost:3000/
  ➜  Network: use --host to expose
  ➜  press h to show help
Error: Missing "./server" export in "vite-plugin-ssr" package
    at bail (file:///Users/franciscoramos/Documents/clau/code/vps-deno/node_modules/.deno/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:14784:8)
    at resolve$1 (file:///Users/franciscoramos/Documents/clau/code/vps-deno/node_modules/.deno/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:14861:10)
    at resolveExports (file:///Users/franciscoramos/Documents/clau/code/vps-deno/node_modules/.deno/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:21850:12)
    at resolveDeepImport (file:///Users/franciscoramos/Documents/clau/code/vps-deno/node_modules/.deno/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:21868:31)
    at tryNodeResolve (file:///Users/franciscoramos/Documents/clau/code/vps-deno/node_modules/.deno/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:21557:20)
    at Context.resolveId (file:///Users/franciscoramos/Documents/clau/code/vps-deno/node_modules/.deno/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:21321:28)
    at Object.resolveId (file:///Users/franciscoramos/Documents/clau/code/vps-deno/node_modules/.deno/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:41407:46)
    at eventLoopTick (ext:core/01_core.js:182:11)
    at async TransformContext.resolve (file:///Users/franciscoramos/Documents/clau/code/vps-deno/node_modules/.deno/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:41154:23)
    at async normalizeUrl (file:///Users/franciscoramos/Documents/clau/code/vps-deno/node_modules/.deno/vite@4.0.3/node_modules/vite/dist/node/chunks/dep-0bae2027.js:39506:34)
[vite-plugin-ssr@0.4.69][Warning] No `_error.page.js` found. We recommend creating a `_error.page.js` file. (This warning is not shown in production.)

```

**Comment by brillout** [comment]
It should work if you respect the `deno.lock` file.

PR welcome to update the dependencies of the example. That should, in principle, work as well since the latest Deno has improved its support for Node.js.
